#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx
# Nginx should be listening on port 80
# Serve a page that returns a "Hello World!" string

echo -e "Updating package list and installing Nginx.\n"
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

echo -e "\nSetting up Nginx configuration.\n"

# Start Nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Give user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup the default index file
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index file with "Hello World!" content
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart Nginx to apply changes
sudo service nginx restart

echo -e "\nNginx has been successfully configured to serve 'Hello World!'. ✅\n"
